"""Coaching Flow Agent

Merges outputs from resume_coach (coaching_session) and interview_map into a
single, phase-gated coaching session plan the candidate can work through
sequentially.

Phase structure
---------------
  Phase 1 — Internship Recall      (coaching_session.internship_drills)
  Phase 2 — Stock Pitch Prep       (coaching_session.pitch_scaffold)
  Phase 3 — Interview Round Sim    (interview_map.rounds)
  Phase 4 — Mock Plan Execution    (interview_map.mock_plan)

Each phase carries:
  phase_id, phase_name, status (pending/active/done),
  source, items, llm_intro, llm_tips

The agent also emits:
  overall_progress  — {total_phases, completed, pct}
  next_action       — human-readable string telling the candidate what to do now
  coaching_tips     — forwarded from interview_map
  weekly_plan       — 7-day action calendar generated by LLM

Usage (graph mode):
  coaching_flow_agent(state) -> {"coaching_flow": {...}}

Usage (standalone / REPL):
  from app.agents.coaching_flow import advance_phase, get_summary
  new_state = advance_phase(state, phase_id=1)
  print(get_summary(state))
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List

from app.llm import generate_json, generate_text
from app.graph.state import InvestmentJobState

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PHASE_DEFS = [
    {
        "phase_id": 1,
        "phase_name": "\u5b9e\u4e60\u7ecf\u5386\u91cd\u6e29",
        "source": "coaching_session.internship_drills",
        "description": "\u9010\u9898\u56de\u7b54\u5b9e\u4e60\u8ffd\u95ee\u9898\uff0c\u5e76\u5bf9\u7167 hint \u81ea\u8bc4\u3002"
        "\u76ee\u6807\uff1a\u80fd\u7528 2 \u53e5\u8bdd\u6e05\u6670 pitch \u6bcf\u6bb5\u5b9e\u4e60\u3002",
    },
    {
        "phase_id": 2,
        "phase_name": "Stock Pitch \u51c6\u5907",
        "source": "coaching_session.pitch_scaffold",
        "description": "\u586b\u5145 pitch \u6a21\u677f\u5e76\u7ec3\u4e60\u8ffd\u95ee\u9898\u3002"
        "\u76ee\u6807\uff1a\u80fd\u6d41\u7545\u5b8c\u6210\u4e00\u4e2a\u5b8c\u6574 5 \u5206\u949f stock pitch\u3002",
    },
    {
        "phase_id": 3,
        "phase_name": "\u9762\u8bd5\u8f6e\u6b21\u6a21\u62df",
        "source": "interview_map.rounds",
        "description": "\u6309\u8f6e\u6b21\u9010\u9898\u6a21\u62df\u4f5c\u7b54\uff0c\u5f55\u97f3\u540e\u5bf9\u7167\u8bc4\u5206\u6807\u51c6\u81ea\u8bc4\u3002"
        "\u76ee\u6807\uff1a\u6bcf\u9898\u4e0d\u8d85\u8fc7 90 \u79d2\u3002",
    },
    {
        "phase_id": 4,
        "phase_name": "Mock Plan \u6267\u884c",
        "source": "interview_map.mock_plan",
        "description": "\u6309 mock_plan \u7684 session \u5b89\u6392\u5b8c\u6210\u6574\u4f53\u6a21\u62df\u3002"
        "\u76ee\u6807\uff1a\u5168\u7a0b\u65e0\u505c\u987f\uff0c\u8fdb\u5165\u771f\u5b9e\u9762\u8bd5\u72b6\u6001\u3002",
    },
]

_NEXT_ACTION_TEMPLATES = {
    0: "\u4ece Phase 1 \u5f00\u59cb\uff1a\u9010\u9898\u56de\u7b54\u5b9e\u4e60\u8ffd\u95ee\u9898\uff0c\u5bf9\u7167 hint \u81ea\u8bc4\u3002",
    1: "Phase 1 \u5b8c\u6210\u2192 Phase 2\uff1a\u586b\u5145 stock pitch \u6a21\u677f\uff0c\u5e76\u5bf9\u7167\u8ffd\u95ee\u9898\u7ec3\u4e60\u3002",
    2: "Phase 2 \u5b8c\u6210\u2192 Phase 3\uff1a\u6309\u8f6e\u6b21\u6a21\u62df\u4f5c\u7b54\uff0c\u5f55\u97f3\u5e76\u81ea\u8bc4\u3002",
    3: "Phase 3 \u5b8c\u6210\u2192 Phase 4\uff1a\u6309 mock plan \u8fdb\u884c\u5b8c\u6574\u6a21\u62df\uff0c\u8fdb\u5165\u771f\u5b9e\u9762\u8bd5\u72b6\u6001\u3002",
    4: "\u5168\u90e8 Phase \u5b8c\u6210 \ud83c\udf89 \u53ef\u4ee5\u5c1d\u8bd5\u5206\u6295\uff0c\u628a\u7b2c\u4e00\u5c01\u5e94\u804c\u90ae\u4ef6\u53d1\u51fa\u53bb\u4e86\u3002",
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_phase_items(phase_def: dict, coaching_session: dict, interview_map: dict) -> List[Any]:
    src = phase_def["source"]
    if src == "coaching_session.internship_drills":
        return coaching_session.get("internship_drills") or []
    if src == "coaching_session.pitch_scaffold":
        scaffold = coaching_session.get("pitch_scaffold")
        return [scaffold] if scaffold else []
    if src == "interview_map.rounds":
        return interview_map.get("rounds") or []
    if src == "interview_map.mock_plan":
        mp = interview_map.get("mock_plan")
        return [mp] if mp else []
    return []


def _llm_phase_intro(phase_def: dict, job_type: str, sector: str) -> str:
    prompt = f"""
\u4f60\u662f\u4e00\u4f4d\u6295\u7814\u6c42\u804c\u6559\u7ec3\u3002\u4e3a\u4ee5\u4e0b Coaching \u9636\u6bb5\u751f\u6210\u4e00\u6bb5\u7b80\u6d01\u7684\u5f00\u573a\u5f15\u5bfc\u8bed\uff08\u4e0d\u8d85\u8fc7 60 \u5b57\uff09\uff0c
\u9762\u5411\u5019\u9009\u4eba\uff0c\u8bed\u6c14\u52a1\u5b9e\u4e0d\u5524\u6162\u3002

\u9636\u6bb5\uff1a{phase_def['phase_name']}
\u76ee\u6807\uff1a{phase_def['description']}
\u5c97\u4f4d\u7c7b\u578b\uff1a{job_type} | \u884c\u4e1a\uff1a{sector}
"""
    fallback = f"\u73b0\u5728\u8fdb\u5165{phase_def['phase_name']}\u3002{phase_def['description']}"
    try:
        return generate_text(prompt, fallback=fallback)
    except Exception:  # noqa: BLE001
        return fallback


def _llm_weekly_plan(
    jd_profile: dict,
    diagnosis: dict,
    coaching_session: dict,
    interview_map: dict,
) -> dict:
    job_type = jd_profile.get("job_type", "equity research")
    sector = jd_profile.get("sector", "generalist")
    gaps = diagnosis.get("gaps", [])
    drill_count = len((coaching_session.get("internship_drills")) or [])
    rounds = len((interview_map.get("rounds")) or [])

    prompt = f"""
\u4f60\u662f\u6295\u7814\u6c42\u804c\u987e\u95ee\u3002\u8bf7\u751f\u6210\u4e00\u4efd\u5177\u4f53\u53ef\u6267\u884c\u768476\u5929\u51c6\u5907\u8ba1\u5212\uff0c\u4ee5 JSON \u8fd4\u56de\u3002

\u5019\u9009\u4eba\u60c5\u51b5\uff1a
- \u5c97\u4f4d\u7c7b\u578b\uff1a{job_type} | \u884c\u4e1a\uff1a{sector}
- \u4e3b\u8981\u77ed\u677f\uff1a{gaps}
- \u5b9e\u4e60\u590d\u76d8\u6bb5\u6570\uff1a{drill_count} \u6bb5
- \u9762\u8bd5\u8f6e\u6b21\uff1a{rounds} \u8f6e

\u8fd4\u56de\u683c\u5f0f\uff1a
{{
  "days": [
    {{"day": 1, "theme": str, "tasks": [str], "duration_min": int, "milestone": str}},
    ...
  ],
  "total_hours": float,
  "key_milestones": [str]
}}
\u8981\u6c42\uff1a
1. \u6bcf\u5929\u4efb\u52a1 2-4 \u9879\uff0c\u6bcf\u9879\u5177\u4f53\u52310\u52a8\u8bcd
2. \u628a 4 \u4e2a Phase \u5747\u5300\u5206\u914d\u5230 7 \u5929
3. \u7b2c 7 \u5929\u8fd4\u56de\u68c0\u67e5\u548c\u5907\u7528\u65b9\u6848
4. \u603b\u65f6\u957f\u5408\u7406\uff08\u6bcf\u5929 2-4 \u5c0f\u65f6\uff09
"""
    fallback = {
        "days": [
            {"day": i, "theme": f"Day {i}", "tasks": ["\u81ea\u5b9a\u4e49\u4efb\u52a1"], "duration_min": 120, "milestone": ""}
            for i in range(1, 8)
        ],
        "total_hours": 14.0,
        "key_milestones": ["Phase 1 \u5b8c\u6210", "Stock pitch \u5b8c\u6210", "\u5168\u8f6e\u6a21\u62df\u5b8c\u6210"],
    }
    try:
        return generate_json(prompt, fallback)
    except Exception:  # noqa: BLE001
        return fallback


# ---------------------------------------------------------------------------
# Core builder
# ---------------------------------------------------------------------------

def _build_coaching_flow(
    jd_profile: dict,
    diagnosis: dict,
    coaching_session: dict,
    interview_map: dict,
) -> dict:
    job_type = jd_profile.get("job_type", "equity research")
    sector = jd_profile.get("sector", "generalist")

    phases = []
    for ph_def in _PHASE_DEFS:
        items = _get_phase_items(ph_def, coaching_session, interview_map)
        intro = _llm_phase_intro(ph_def, job_type, sector)
        phases.append({
            "phase_id": ph_def["phase_id"],
            "phase_name": ph_def["phase_name"],
            "status": "pending",
            "source": ph_def["source"],
            "description": ph_def["description"],
            "llm_intro": intro,
            "items": items,
            "item_count": len(items),
        })

    completed = sum(1 for p in phases if p["status"] == "done")
    total = len(phases)
    pct = round(completed / total * 100) if total else 0

    weekly_plan = _llm_weekly_plan(jd_profile, diagnosis, coaching_session, interview_map)

    coaching_tips = interview_map.get("coaching_tips") or [
        "\u6bcf\u9898\u4e0d\u8d85\u8fc7 90 \u79d2",
        "\u4e0d\u8981\u80cc\u7a3f",
        "wind-down \u65f6\u4e3b\u52a8\u95ee\u4e00\u4e2a\u806a\u660e\u7684\u95ee\u9898",
    ]

    return {
        "phases": phases,
        "overall_progress": {
            "total_phases": total,
            "completed": completed,
            "pct": pct,
        },
        "next_action": _NEXT_ACTION_TEMPLATES.get(completed, _NEXT_ACTION_TEMPLATES[0]),
        "coaching_tips": coaching_tips,
        "weekly_plan": weekly_plan,
        "meta": {
            "job_type": job_type,
            "sector": sector,
            "total_items": sum(p["item_count"] for p in phases),
        },
    }


# ---------------------------------------------------------------------------
# Public agent (graph mode)
# ---------------------------------------------------------------------------

def coaching_flow_agent(state: InvestmentJobState) -> Dict[str, Any]:
    jd_profile = state.get("jd_profile") or {}
    diagnosis = state.get("diagnosis") or {}
    coaching_session = state.get("coaching_session") or {}
    interview_map = state.get("interview_map") or {}

    coaching_flow = _build_coaching_flow(
        jd_profile=jd_profile,
        diagnosis=diagnosis,
        coaching_session=coaching_session,
        interview_map=interview_map,
    )

    total = coaching_flow["meta"]["total_items"]
    logger.info(
        "coaching_flow_agent: %d phases built, %d total items.",
        len(coaching_flow["phases"]),
        total,
    )
    return {"coaching_flow": coaching_flow}


# ---------------------------------------------------------------------------
# Standalone helpers (call directly, not via graph)
# ---------------------------------------------------------------------------

def advance_phase(state: InvestmentJobState, phase_id: int) -> InvestmentJobState:
    """Mark a phase as done and update progress. Returns updated state."""
    cf = dict(state.get("coaching_flow") or {})
    phases = [dict(p) for p in cf.get("phases", [])]
    for p in phases:
        if p["phase_id"] == phase_id:
            p["status"] = "done"
    completed = sum(1 for p in phases if p["status"] == "done")
    total = len(phases)
    cf["phases"] = phases
    cf["overall_progress"] = {
        "total_phases": total,
        "completed": completed,
        "pct": round(completed / total * 100) if total else 0,
    }
    cf["next_action"] = _NEXT_ACTION_TEMPLATES.get(completed, _NEXT_ACTION_TEMPLATES[4])
    return {**state, "coaching_flow": cf}


def get_summary(state: InvestmentJobState) -> str:
    """Return a human-readable coaching flow summary."""
    cf = state.get("coaching_flow") or {}
    if not cf:
        return "coaching_flow not yet generated. Run coaching_flow_agent first."
    prog = cf.get("overall_progress", {})
    lines = [
        f"=== Coaching Flow Summary ===",
        f"Progress: {prog.get('completed', 0)}/{prog.get('total_phases', 4)} phases "
        f"({prog.get('pct', 0)}%)",
        f"Next: {cf.get('next_action', '')}",
        "",
        "Phases:",
    ]
    for p in cf.get("phases", []):
        status_icon = "\u2705" if p["status"] == "done" else "\u23f3"
        lines.append(
            f"  {status_icon} Phase {p['phase_id']}: {p['phase_name']} "
            f"({p['item_count']} items) [{p['status']}]"
        )
    lines.append("")
    lines.append("Weekly Plan Milestones:")
    for ms in (cf.get("weekly_plan") or {}).get("key_milestones", []):
        lines.append(f"  • {ms}")
    return "\n".join(lines)
